# Generated by Django 5.1.4 on 2025-01-17 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0004_alter_yard_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentyard',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='yard_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
