# Generated by Django 5.1.4 on 2025-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0010_alter_commentyard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentyard',
            name='user',
        ),
    ]
