# Generated by Django 5.1.4 on 2025-01-11 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwirek', '0004_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='yard_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
