# Generated by Django 5.1.4 on 2025-01-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwirek', '0007_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
