# Generated by Django 5.1.4 on 2025-01-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentyard',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='number_of_comments', to='yard.yard'),
        ),
    ]
