# Generated by Django 5.1.4 on 2025-01-27 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0004_alter_replytocommentyard_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplyToCommentYard',
            new_name='ReplyToYardComment',
        ),
    ]
