# Generated by Django 5.1.4 on 2025-01-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0005_alter_commentyard_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentyard',
            name='comments',
        ),
        migrations.AlterField(
            model_name='commentyard',
            name='body',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='commentyard',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yard.yard'),
        ),
    ]
