# Generated by Django 5.1.4 on 2025-01-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0005_rename_replytocommentyard_replytoyardcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytoyardcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='yard.commentyard'),
        ),
    ]
