# Generated by Django 5.1.4 on 2025-01-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0006_alter_replytoyardcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentyard',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='yard.yard'),
        ),
    ]
