# Generated by Django 5.1.4 on 2025-02-01 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0009_commentyard_dislikes_commentyard_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='test_author',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
