# Generated by Django 5.1.4 on 2025-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0010_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to='images/'),
        ),
    ]
