# Generated by Django 5.1.4 on 2025-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
