# Generated by Django 5.1.4 on 2025-02-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0013_alter_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='yard_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/yard/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_pic.png', upload_to='images/profile/'),
        ),
    ]
