# Generated by Django 5.1.4 on 2025-01-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0013_rename_is_read_notifications_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='link',
        ),
    ]
