# Generated by Django 5.1.4 on 2025-01-31 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0014_remove_notifications_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='yard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_yard_id', to='yard.yard'),
        ),
    ]
