# Generated by Django 5.1.4 on 2025-01-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0015_notifications_yard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='yard',
        ),
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
